# -*- coding: utf-8 -*-
"""AAPL EMA Stock Trade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/156MsjrfuculBe8BIj25rfO_RwkN1Dnvm
"""

#Import the libraries
import math
import pandas_datareader as web
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
import plotly.offline as py
plt.style.use('fivethirtyeight')

#Get the Stock Quote: The price of a stock as quoted on an exchange
df = web.DataReader('AAPL', data_source='yahoo', start='2020-01-02', end='2021-01-05') #end = '2017-12-31', format = 'YYYY-MM-DD'
#Show the data
df

#Visualize the closing price history
plt.figure(figsize=(16,8))
plt.title('AAPL Close Price History')
plt.plot(df['Close'])
plt.xlabel('Date',fontsize=18)
plt.ylabel('Close Price USD ($)',fontsize=18)
plt.show()

ShortEMA = df.Close.ewm(span=9,adjust=False).mean()
MidEMA = df.Close.ewm(span=21,adjust=False).mean()
LongEMA = df.Close.ewm(span=55,adjust=False).mean()
#ShortGold = df.Close.ewm(span=50,adjust=False).mean()
#LongGold = df.Close.ewm(span=200,adjust=False).mean()

#Visualize the closing price history
plt.figure(figsize=(16,8))
plt.title('AAPL Close Price History')
plt.plot(df['Close'],label='Close Price')
plt.plot(ShortEMA, label='Short EMA',color='green',alpha=0.6)
plt.plot(MidEMA, label='Mid EMA',alpha=0.6)
plt.plot(LongEMA, label='Long EMA',alpha=0.6)
plt.legend(['Close Price','Short 9EMA','Mid 21EMA', 'Long 55EMA'], loc='lower right')
#plt.plot(ShortGold, label='ShortGold',alpha=0.6,color='gold')
#plt.plot(LongGold, label='LongGold',alpha=0.6)
plt.xlabel('Date',fontsize=18)
plt.ylabel('Close Price USD ($)',fontsize=18)
plt.show()

df['Short EMA']=ShortEMA
df['Mid EMA']=MidEMA
df['Long EMA']=LongEMA

df

def sell_buy(data):
  buy_list=[]
  sell_list=[]
  long_flag=False
  short_flag=False

  for i in range(0,len(data)):
    if data['Mid EMA'][i] < data['Long EMA'][i] and data ['Short EMA'][i]< data ['Mid EMA'][i] and long_flag == False and short_flag == False:
      buy_list.append(data['Close'][i])
      sell_list.append(np.nan)
      short_flag=True
    elif short_flag==True and data ['Short EMA'][i] > data ['Mid EMA'][i]:
      sell_list.append(data['Close'][i])
      buy_list.append(np.nan)
      short_flag  = False
    elif data['Mid EMA'][i] > data['Long EMA'][i] and data ['Short EMA'][i]> data ['Mid EMA'][i] and long_flag == False and short_flag == False:
      buy_list.append(data['Close'][i])
      sell_list.append(np.nan)
      long_flag=True
    elif long_flag==True and data ['Short EMA'][i] < data ['Mid EMA'][i]:
      sell_list.append(data['Close'][i])
      buy_list.append(np.nan)
      long_flag  = False
    else:
      buy_list.append(np.nan)
      sell_list.append(np.nan)

  return (buy_list,sell_list)

df['Buy']= sell_buy(df)[0]
df['Sell']= sell_buy(df)[1]
df[['Buy','Sell']]

plt.figure(figsize=(16,8))
plt.title('AAPL Close Price History')
plt.plot(df['Close'],label='Close Price',alpha=0.5)
plt.plot(ShortEMA, label='Short EMA',color='green',alpha=0.35)
plt.plot(MidEMA, label='Mid EMA',alpha=0.35)
plt.plot(LongEMA, label='Long EMA',color='gold',alpha=0.35)
plt.scatter(df.index, df['Buy'], color = 'green', marker='^',alpha=1)
plt.scatter(df.index, df['Sell'], color = 'red', marker='v',alpha=1)
plt.legend(['Close Price','Short 9EMA','Mid 21EMA', 'Long 55EMA','Buy' ,'Sell'], loc='lower right')
plt.xlabel('Date',fontsize=18)
plt.ylabel('Close Price USD ($)',fontsize=18)
plt.show()

df['Buy']= sell_buy(df)[0]
df['Sell']= sell_buy(df)[1]

sellsum = df['Sell'].sum(min_count=0)
buysum = df['Buy'].sum(min_count=0)
last_day_price= df['Close'].iloc[-1]
profit= float (sellsum) - float (buysum) + float(last_day_price)
print(profit)
df